### ISSUE TITLE
Is there any paper about this code?

### ISSUE THREAD

**Issue by TicusFFF** [gauss5930/LLM-Agora#3]
Hello, thank you for this project. It has greatly assisted my work. I would like to know if there are any papers related to this code that I can cite, apart from "Improving Factuality and Reasoning in Language Models through Multiagent Debate."
Thank you very much for your help :)

**Comment by gauss5930** [comment]
Hi @know-nothing8 ! Thank you for your interest in my project! Indeed, I only cited the paper you mentioned for this project, so I have no ideas about papers related to this concept 🥲 It is great to hear that my project helped your work, and I hope your project goes well. I hope you cite this repo in your project if my project helped you a lot!

**Comment by TicusFFF** [comment]
Thank you very much for your quick response @gauss5930 ! Your work has been incredibly helpful, and I will definitely cite your repository in my work. Thanks again!
